ALTER TABLE [dbo].[ABRANGENCIA_CURSO] WITH NOCHECK ADD 
	CONSTRAINT [PK_ABRANGENCIA_CURSO] PRIMARY KEY  CLUSTERED 
	(
		[ONDA_CD_ONDA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ADMINISTRADOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_ADMI] PRIMARY KEY  CLUSTERED 
	(
		[ADMI_CD_CHAVE]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[APOIO_LOCAL_CURSO] WITH NOCHECK ADD 
	CONSTRAINT [PK_APOIO_LOCAL_CURSO] PRIMARY KEY  CLUSTERED 
	(
		[USMA_CD_USUARIO],
		[APLO_NR_ATRIBUICAO],
		[CURS_CD_CURSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[APOIO_LOCAL_MODULO_ORGAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_APOIO_LOCAL_MODULO_ORGAO] PRIMARY KEY  CLUSTERED 
	(
		[USMA_CD_USUARIO],
		[APLO_NR_ATRIBUICAO],
		[SUMO_NR_CD_SEQUENCIA],
		[ORME_CD_ORG_MENOR]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[AUDITOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_AUDI] PRIMARY KEY  CLUSTERED 
	(
		[AUDI_CHAVE]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[BACKLOG] WITH NOCHECK ADD 
	CONSTRAINT [PK_BACKLOG] PRIMARY KEY  CLUSTERED 
	(
		[BALO_CD_COD_BACKLOG]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[BACKLOG_CHAVE] WITH NOCHECK ADD 
	CONSTRAINT [PK_BACKLOG_CHAVE] PRIMARY KEY  CLUSTERED 
	(
		[USMA_CD_USUARIO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CASE_CONDICAO_TRANS] WITH NOCHECK ADD 
	CONSTRAINT [PK_CASE_CONDICAO_TRANS] PRIMARY KEY  CLUSTERED 
	(
		[CASE_TX_CD_CASE],
		[CASE_NR_CD_CONDICAO],
		[TRAN_CD_TRANSACAO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CENARIO_CONDICAO_TRANS] WITH NOCHECK ADD 
	CONSTRAINT [PK_CENARIO_CONDICAO_TRANS] PRIMARY KEY  CLUSTERED 
	(
		[CASE_TX_CD_CASE],
		[CASE_NR_CD_CONDICAO],
		[TRAN_CD_TRANSACAO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CENARIO_DESENV_CANCELADO] WITH NOCHECK ADD 
	CONSTRAINT [PK_CENARIO_DESENV_CANCELADO] PRIMARY KEY  CLUSTERED 
	(
		[CENA_CD_CENARIO],
		[CETR_NR_SEQUENCIA]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CLI] WITH NOCHECK ADD 
	CONSTRAINT [PK_CLI] PRIMARY KEY  CLUSTERED 
	(
		[USMA_CD_USUARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CLI_ORGAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_CLI_ORGAO] PRIMARY KEY  CLUSTERED 
	(
		[USMA_CD_USUARIO],
		[ORME_CD_ORG_MENOR]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CURSO_CORRELATO] WITH NOCHECK ADD 
	CONSTRAINT [PK_CURSO_CORRELATO] PRIMARY KEY  CLUSTERED 
	(
		[CURS_CD_CURSO],
		[CURS_CD_CURSO_CORRELATO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CURSO_FUNCAO_TODAS] WITH NOCHECK ADD 
	CONSTRAINT [PK_CURSO_FUNCAO_TODAS] PRIMARY KEY  CLUSTERED 
	(
		[CURS_CD_CURSO],
		[FUNE_CD_FUNCAO_NEGOCIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CURSO_TRANSACAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_CURSO_TRANSACAO] PRIMARY KEY  CLUSTERED 
	(
		[TRAN_CD_TRANSACAO],
		[CURS_CD_CURSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[DELEGADO] WITH NOCHECK ADD 
	CONSTRAINT [PK_DELE] PRIMARY KEY  CLUSTERED 
	(
		[DELE_CD_CHAVE],
		[DELE_CD_ORG_MENOR]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[EMPREGADO_EXCECAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_EMEX] PRIMARY KEY  CLUSTERED 
	(
		[EMEX_CD_CHAVE]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ETL_CONTROLE] WITH NOCHECK ADD 
	CONSTRAINT [PK_ETL_CONTROLE] PRIMARY KEY  CLUSTERED 
	(
		[CONT_TX_IDENTIFICADOR]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUNCAO_NEGOCIO_SUB_MODULO] WITH NOCHECK ADD 
	CONSTRAINT [PK_FUNCAO_SUB_MODULO] PRIMARY KEY  CLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[SUMO_NR_CD_SEQUENCIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUNCAO_USUARIO_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_FUNCAO_USUARIO_PERFIL] PRIMARY KEY  CLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MIPE_NR_SEQ_MICRO_PERFIL],
		[USMA_CD_USUARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUNCAO_USUARIO_PERFIL_AUX] WITH NOCHECK ADD 
	CONSTRAINT [PK_FUNCAO_USUARIO_PERFIL_AUX] PRIMARY KEY  CLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MIPE_NR_SEQ_MICRO_PERFIL],
		[USMA_CD_USUARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUNCAO_USUARIO_PERFIL_VISAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_FUNCAO_USUARIO_PERFIL_VISAO] PRIMARY KEY  CLUSTERED 
	(
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MIPE_NR_SEQ_MICRO_PERFIL],
		[USMA_CD_USUARIO],
		[VISA_NR_SEQ_VISAO],
		[FUNE_CD_FUNCAO_NEGOCIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUN_ORIEN_MEGA_MODULO] WITH NOCHECK ADD 
	CONSTRAINT [PK_FUN_ORIEN_MEGA_MODULO] PRIMARY KEY  CLUSTERED 
	(
		[MEPR_CD_MEGA_PROCESSO],
		[SUMO_NR_CD_SEQUENCIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GERENTE_DELEGADO_LOTACAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_GERENTE_DELEGADO_LOTACAO] PRIMARY KEY  CLUSTERED 
	(
		[USMA_CD_USUARIO],
		[ORME_CD_ORG_MENOR]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GOLI_FUNCAO_USUARIO] WITH NOCHECK ADD 
	CONSTRAINT [PK_GOLI_FUNCAO_USUARIO] PRIMARY KEY  CLUSTERED 
	(
		[LOTE_NR_SEQ_LOTE],
		[USMA_CD_USUARIO],
		[FUNE_CD_FUNCAO_NEGOCIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GOLI_FUNCAO_USUARIO_COM_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_GOLI_FUNCAO_USUARIO_COM_PERFIL] PRIMARY KEY  CLUSTERED 
	(
		[LOTE_NR_SEQ_LOTE],
		[USMA_CD_USUARIO],
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MIPE_NR_SEQ_MICRO_PERFIL]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GOLI_FUNCAO_USUARIO_COM_PERFIL_RH] WITH NOCHECK ADD 
	CONSTRAINT [PK_GOLI_FUNCAO_USUARIO_COM_PERFIL_RH] PRIMARY KEY  CLUSTERED 
	(
		[LOTE_NR_SEQ_LOTE],
		[USMA_CD_USUARIO],
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MIPE_NR_SEQ_MICRO_PERFIL],
		[VISA_NR_SEQ_VISAO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GOLI_FUNCAO_USUARIO_SEM_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_GOLI_FUNCAO_USUARIO_SEM_PERFIL] PRIMARY KEY  CLUSTERED 
	(
		[LOTE_NR_SEQ_LOTE],
		[USMA_CD_USUARIO],
		[FUNE_CD_FUNCAO_NEGOCIO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_CENTRO_TREINAMENTO] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_CENTRO_TREINAMENTO] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[CTRO_CD_CENTRO_TREINAMENTO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_CORTE] WITH NOCHECK ADD 
	CONSTRAINT [PK_CORTE] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_CURSO] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_CURSO] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[CURS_CD_CURSO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_CURSO_PRE_REQUISITO] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_CURSO_PRE_REQUISITO] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[CURS_CD_CURSO],
		[CURS_PRE_REQUISITO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_CURSO_UNIDADE] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_CURSO_UNIDADE] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[CURS_CD_CURSO],
		[UNID_CD_UNIDADE]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_DEMANDA_ORIGINAL] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_DEMANDA_ORIGINAL] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[ORLO_CD_ORG_LOT],
		[ORME_CD_ORG_MENOR],
		[CURS_CD_CURSO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_DEMANDA_ORIGINAL_RECUSADA] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_DEMANDA_ORIGINAL_RECUSADA] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[ORLO_CD_ORG_LOT],
		[ORME_CD_ORG_MENOR],
		[CURS_CD_CURSO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_DIRETORIA] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_DIRETORIA] PRIMARY KEY  CLUSTERED 
	(
		[ORLO_CD_ORG_LOT]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_FERIADO] WITH NOCHECK ADD 
	CONSTRAINT [PK_FERIADO] PRIMARY KEY  CLUSTERED 
	(
		[FERI_CD_FERIADO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_FERIADO_SALA] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_FERIADO_SALA] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[SALA_CD_SALA],
		[FERI_CD_FERIADO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_LOCALIDADE] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOCALIDADE] PRIMARY KEY  CLUSTERED 
	(
		[LOC_CD_LOCALIDADE]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_MULTIPLICADOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_MULTIPLICADOR] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[MULT_NR_CD_ID_MULT]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_MULTIPLICADOR_CURSO] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_MULTIPLICADOR_CURSO] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[MULT_NR_CD_ID_MULT],
		[CURS_CD_CURSO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_MULTIPLICADOR_ORGAO_MENOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_MULTIPLICADOR_ORGAO_MENOR] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[MULT_NR_CD_ID_MULT],
		[ORME_CD_ORG_MENOR]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_ORGAO_MAIOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_ORGAO_MAIOR] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[ORLO_CD_ORG_LOT]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_ORGAO_MENOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_ORGAO_MENOR] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[ORME_CD_ORG_MENOR]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_SALA] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_SALA] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[SALA_CD_SALA]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_TURMA] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_TURMA] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[TURM_NR_CD_TURMA]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_TURMA_UNIDADE] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_TURMA_UNIDADE] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[TURM_NR_CD_TURMA],
		[UNID_CD_UNIDADE]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_UNIDADE] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_UNIDADE] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[UNID_CD_UNIDADE]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_UNIDADE_ORGAO_MENOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_UNIDADE_ORGAO_MENOR] PRIMARY KEY  CLUSTERED 
	(
		[CORT_CD_CORTE],
		[UNID_CD_UNIDADE],
		[ORME_CD_ORG_MENOR]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRADE_USUARIO] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRADE_USUARIO] PRIMARY KEY  CLUSTERED 
	(
		[USUA_CD_USUARIO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[HISTORICO_CONSULTA] WITH NOCHECK ADD 
	CONSTRAINT [PK_HICO] PRIMARY KEY  CLUSTERED 
	(
		[HICO_CD_APROVADOR],
		[HICO_CD_SOLICITANTE],
		[HICO_NR_CONSULTA],
		[MIPE_NR_SEQ_MICRO_PERFIL],
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LOG_CONFLITANTE] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOCO] PRIMARY KEY  CLUSTERED 
	(
		[LOCO_CD_FUNCAO_NEGOCIO],
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LOG_CRITICA] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOCR] PRIMARY KEY  CLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LOG_MAPEAMENTO_OPERACAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOG_MAPEAMENTO_OPERACAO] PRIMARY KEY  CLUSTERED 
	(
		[LMOP_CD_CODIGO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[LOG_TREINAMENTO] WITH NOCHECK ADD 
	CONSTRAINT [PK_LOTR] PRIMARY KEY  CLUSTERED 
	(
		[LOTR_CD_CURSO],
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MICRO_HISTORICO_VALIDACAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_MICRO_HISTORICO_VALIDACAO] PRIMARY KEY  CLUSTERED 
	(
		[MHVA_NR_SEQUENCIA_HIST],
		[MICR_TX_SEQ_MICRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MICRO_R3_VISAO_R3] WITH NOCHECK ADD 
	CONSTRAINT [PK_MICRO_R3_VISAO_R3] PRIMARY KEY  CLUSTERED 
	(
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MIPE_NR_SEQ_MICRO_PERFIL],
		[VISA_NR_SEQ_VISAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MOTIVO] WITH NOCHECK ADD 
	CONSTRAINT [PK_MOTIVO] PRIMARY KEY  CLUSTERED 
	(
		[MOTI_NR_CD_MOTIVO]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORGAO_AGLUTINADOR_EXCECAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORGAO_AGLUTINADO_EXCECAO] PRIMARY KEY  CLUSTERED 
	(
		[AGLU_CD_AGLUTINADO],
		[ORLO_CD_ORG_LOT]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORGAO_MAIOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORGAO_MAIOR] PRIMARY KEY  CLUSTERED 
	(
		[ORLO_CD_ORG_LOT],
		[ORLO_NR_ORDEM]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORLO_FUNC_BLOQUEIO] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORLO_FUNC_BLOQUEIO] PRIMARY KEY  CLUSTERED 
	(
		[ORLO_CD_ORG_LOT],
		[FUNE_CD_FUNCAO_NEGOCIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORLO_FUNC_BLOQUEIO_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORLO_FUNC_BLOQUEIO_PERFIL] PRIMARY KEY  CLUSTERED 
	(
		[ORLO_CD_ORG_LOT],
		[FUNE_CD_FUNCAO_NEGOCIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORLO_MEGA_BLOQUEIO] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORGAO_MEGA_BLOQUEIO] PRIMARY KEY  CLUSTERED 
	(
		[ORLO_CD_ORG_LOT],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORLO_MEGA_BLOQUEIO_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORLO_MEGA_BLOQUEIO_PERFIL] PRIMARY KEY  CLUSTERED 
	(
		[ORLO_CD_ORG_LOT],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORME_FUNC_BLOQUEIO] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORME_FUNC_BLOQUEIO] PRIMARY KEY  CLUSTERED 
	(
		[ORME_CD_ORG_MENOR],
		[FUNE_CD_FUNCAO_NEGOCIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORME_FUNC_BLOQUEIO_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORME_FUNC_BLOQUEIO_PERFIL] PRIMARY KEY  CLUSTERED 
	(
		[ORME_CD_ORG_MENOR],
		[FUNE_CD_FUNCAO_NEGOCIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORME_MEGA_BLOQUEIO] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORME_MEGA_BLOQUEIO] PRIMARY KEY  CLUSTERED 
	(
		[ORME_CD_ORG_MENOR],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORME_MEGA_BLOQUEIO_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORME_MEGA_BLOQUEIO_PERFIL] PRIMARY KEY  CLUSTERED 
	(
		[ORME_CD_ORG_MENOR],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PACOTE_TESTES] WITH NOCHECK ADD 
	CONSTRAINT [PK_PACOTE_TESTES] PRIMARY KEY  CLUSTERED 
	(
		[PCTE_TX_PACT_TESTE],
		[PCTE_NM_VERSAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PASSO_A_PASSO] WITH NOCHECK ADD 
	CONSTRAINT [PK_PASSO_A_PASSO] PRIMARY KEY  CLUSTERED 
	(
		[MEPR_CD_MEGA_PROCESSO],
		[PROC_CD_PROCESSO],
		[SUPR_CD_SUB_PROCESSO],
		[PASS_NR_SEQUENCIAL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PERFIL_ORIEN_GERAL] WITH NOCHECK ADD 
	CONSTRAINT [PK_PERFIL_ORIEN_GERAL] PRIMARY KEY  CLUSTERED 
	(
		[ORIE_NR_SEQUENCIAL]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PERFIL_ORIEN_GERAL_TERMOS] WITH NOCHECK ADD 
	CONSTRAINT [PK_PERFIL_ORIEN_GERAL_TERMOS] PRIMARY KEY  CLUSTERED 
	(
		[ORTE_NR_SEQUENCIAL]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PERFIL_ORIEN_MEGA] WITH NOCHECK ADD 
	CONSTRAINT [PK_PERFIL_ORIEN_MEGA] PRIMARY KEY  CLUSTERED 
	(
		[MEPR_CD_MEGA_PROCESSO],
		[ORIE_NR_SEQUENCIAL]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PERFIL_ORIEN_MEGA_MODULO] WITH NOCHECK ADD 
	CONSTRAINT [PK_PERFIL_ORIEN_MEGA_MODULO] PRIMARY KEY  CLUSTERED 
	(
		[MEPR_CD_MEGA_PROCESSO],
		[SUMO_NR_CD_SEQUENCIA]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PERFIL_ORIEN_MEGA_TERMOS] WITH NOCHECK ADD 
	CONSTRAINT [PK_PERFIL_ORIEN_MEGA_TERMOS] PRIMARY KEY  CLUSTERED 
	(
		[MEPR_CD_MEGA_PROCESSO],
		[ORTE_NR_SEQUENCIAL]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PERFIL_PROPRIETARIO] WITH NOCHECK ADD 
	CONSTRAINT [PK_PERFIL_PROPRIETARIO] PRIMARY KEY  CLUSTERED 
	(
		[USUA_CD_USUARIO],
		[MIPE_NR_SEQ_MICRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO


ALTER TABLE [dbo].[SOLICITACAO_FUNCAO] WITH NOCHECK ADD 
	CONSTRAINT [Solicitacao_Funcao_PK] PRIMARY KEY  CLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SOLICITACAO_MEGA_PROCESSO] WITH NOCHECK ADD 
	CONSTRAINT [Solicitacao_Mega_Processo_PK] PRIMARY KEY  CLUSTERED 
	(
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SOLICITACAO_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_SOPE] PRIMARY KEY  CLUSTERED 
	(
		[MIPE_NR_SEQ_MICRO_PERFIL],
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SOLICITACAO_PERFIL_VISAO] WITH NOCHECK ADD 
	CONSTRAINT [Solicitacao_Perfil_Visao_PK] PRIMARY KEY  CLUSTERED 
	(
		[VISA_NR_SEQ_VISAO],
		[MIPE_NR_SEQ_MICRO_PERFIL],
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SUB_MODULO] WITH NOCHECK ADD 
	CONSTRAINT [PK_SUB_MODULO] PRIMARY KEY  CLUSTERED 
	(
		[SUMO_NR_CD_SEQUENCIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[T30] WITH NOCHECK ADD 
	CONSTRAINT [PK_T30] PRIMARY KEY  CLUSTERED 
	(
		[C536870912]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[USUARIO_APROVADO] WITH NOCHECK ADD 
	CONSTRAINT [PK_USUARIO_APROVADO] PRIMARY KEY  CLUSTERED 
	(
		[USAP_CD_USUARIO],
		[CURS_CD_CURSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[USUARIO_FILTRO] WITH NOCHECK ADD 
	CONSTRAINT [PK_USUARIO_FILTRO] PRIMARY KEY  CLUSTERED 
	(
		[USMA_CD_USUARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[USUARIO_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK_USUARIO_PERFIL] PRIMARY KEY  CLUSTERED 
	(
		[USPE_CD_USUARIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MIPE_NR_SEQ_MICRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[USUARIO_PERFIL_FUNCAOY] WITH NOCHECK ADD 
	CONSTRAINT [PK_USUARIO_PERFIL_FUNCAOY] PRIMARY KEY  CLUSTERED 
	(
		[USPE_CD_USUARIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MIPE_NR_SEQ_MICRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[VISAO_R3] WITH NOCHECK ADD 
	CONSTRAINT [PK_VISAO_R3] PRIMARY KEY  CLUSTERED 
	(
		[VISA_NR_SEQ_VISAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_ACESSO] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_ACESSO] PRIMARY KEY  CLUSTERED 
	(
		[USUA_CD_USUARIO],
		[ONDA_CD_ONDA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_EQUIPE_SINERGIA] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_EQUIPE_SINERGIA] PRIMARY KEY  CLUSTERED 
	(
		[USUA_TX_CD_USUARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_PLANO_ENT_PRODUCAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_PLANO_ENT_PRODUCAO] PRIMARY KEY  CLUSTERED 
	(
		[PLAN_NR_SEQUENCIA_PLANO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_GERAL] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPET_PLANO_TAREFA_GERAL] PRIMARY KEY  CLUSTERED 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PAC] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_PLANO_TAREFA_PAC] PRIMARY KEY  CLUSTERED 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PAI] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_AAA] PRIMARY KEY  CLUSTERED 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PCD] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_PLANO_TAREFA_PCD] PRIMARY KEY  CLUSTERED 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PCM] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_AAA_1] PRIMARY KEY  CLUSTERED 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PPCM_NR_SEQUENCIA_TAREFA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PDS] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_PLANO_TAREFA_PDS] PRIMARY KEY  CLUSTERED 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PPO] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_PPO_PLANO_ETAPA] PRIMARY KEY  CLUSTERED 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_SISTEMA_LEGADO] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_SISTEMA_LEGADO] PRIMARY KEY  CLUSTERED 
	(
		[SIST_NR_SEQUENCIAL_SISTEMA_LEGADO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_TAREFA_DESENVOLVIMENTO] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_TAREFA_DESENVOLVIMENTO] PRIMARY KEY  CLUSTERED 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA],
		[PPCD_NR_SEQUENCIA_FUNC],
		[DESE_CD_DESENVOLVIMENTO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_TAREFA_RESPONSAVEL] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_TAREFA_RESPONSAVEL] PRIMARY KEY  CLUSTERED 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA],
		[USUA_TX_CD_USUARIO],
		[TPRE_NR_TIPO_RESPONSABILIDADE]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_TIPO_RESPONSABILIDADE] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_TIPO_RESPONSABILIDADE] PRIMARY KEY  CLUSTERED 
	(
		[TPRE_NR_TIPO_RESPONSABILIDADE]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[XPEP_USUARIO] WITH NOCHECK ADD 
	CONSTRAINT [PK_XPEP_USUARIO] PRIMARY KEY  CLUSTERED 
	(
		[USUA_CD_USUARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ACESSO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[USUA_CD_USUARIO],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[APOIO_LOCAL_MODULO] WITH NOCHECK ADD 
	CONSTRAINT [PK_APOIO_LOCAL_MODULO] PRIMARY KEY  NONCLUSTERED 
	(
		[USMA_CD_USUARIO],
		[APLO_NR_ATRIBUICAO],
		[SUMO_NR_CD_SEQUENCIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[APOIO_LOCAL_MULT] WITH NOCHECK ADD 
	CONSTRAINT [PK_APOIO_LOCAL_MULT] PRIMARY KEY  NONCLUSTERED 
	(
		[USMA_CD_USUARIO],
		[APLO_NR_ATRIBUICAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[APOIO_LOCAL_ONDA] WITH NOCHECK ADD 
	CONSTRAINT [PK_APOIO_LOCAL_ONDA] PRIMARY KEY  NONCLUSTERED 
	(
		[USMA_CD_USUARIO],
		[APLO_NR_ATRIBUICAO],
		[ONDA_CD_ONDA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[APOIO_LOCAL_ORGAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_APOIO_LOCAL_ORGAO] PRIMARY KEY  NONCLUSTERED 
	(
		[USMA_CD_USUARIO],
		[APLO_NR_ATRIBUICAO],
		[ORME_CD_ORG_MENOR]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ATIVIDADE_CARGA] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[ATCA_CD_ATIVIDADE_CARGA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ATIVIDADE_CARGA_EMPRESA_UNID] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[ATCA_CD_ATIVIDADE_CARGA],
		[EMPR_CD_NR_EMPRESA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[BPP] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[BPPP_CD_BPP]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[BPP_TRANSACAO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[BPPP_CD_BPP],
		[TRAN_CD_TRANSACAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[BUG_IMPORT] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[BUG_CD_BUG],
		[BUG_NR_SEQUENCIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CENARIO] WITH NOCHECK ADD 
	CONSTRAINT [PK__CENARIO__65238F17] PRIMARY KEY  NONCLUSTERED 
	(
		[CENA_CD_CENARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CENARIO_TRANSACAO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[CENA_CD_CENARIO],
		[CETR_NR_SEQUENCIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CENARIO_VALIDACAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_CENARIO_VALIDACAO] PRIMARY KEY  NONCLUSTERED 
	(
		[CENA_CD_CENARIO],
		[CEVA_NR_SEQUENCIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CLASSE_CENARIO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[CLCE_CD_NR_CLASSE_CENARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CLASSE_CENARIO_MEGA_PROCESSO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[CLCE_CD_NR_CLASSE_CENARIO],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CURSO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[CURS_CD_CURSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CURSO_CENARIO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[CENA_CD_CENARIO],
		[CURS_CD_CURSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CURSO_FUNCAO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[CURS_CD_CURSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CURSO_PRE_REQUISITO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[CURS_CD_CURSO],
		[CUPR_NR_SEQUENCIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CURSO_PRE_REQUISITO_ALTER] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[CUPR_NR_SEQUENCIA],
		[CUPR_NR_ALTERNATIVO],
		[CURS_CD_CURSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[DESENVOLVIMENTO] WITH NOCHECK ADD 
	CONSTRAINT [PK__DESENVOLVIMENTO__72C60C4A] PRIMARY KEY  NONCLUSTERED 
	(
		[DESE_CD_DESENVOLVIMENTO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[EMPRESA_UNIDADE] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[EMPR_CD_NR_EMPRESA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FECHA_ESCOPO] WITH NOCHECK ADD 
	CONSTRAINT [PK_FECHA_ESCOPO] PRIMARY KEY  NONCLUSTERED 
	(
		[FEES_CD_FECHAMENTO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FECHA_HISTORICO_CENARIO] WITH NOCHECK ADD 
	CONSTRAINT [PK_FECHA_HISTORICO_CENARIO] PRIMARY KEY  NONCLUSTERED 
	(
		[CENA_CD_CENARIO],
		[FEES_CD_FECHAMENTO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FECHA_HISTORICO_CENA_TRANS] WITH NOCHECK ADD 
	CONSTRAINT [PK_FECHA_HISTORICO_CENA_TRANS] PRIMARY KEY  NONCLUSTERED 
	(
		[FEES_CD_FECHAMENTO],
		[CENA_CD_CENARIO],
		[CETR_NR_SEQUENCIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FECHA_HISTORICO_DECOMP] WITH NOCHECK ADD 
	CONSTRAINT [PK_FECHA_HISTORICO_DECOMP] PRIMARY KEY  NONCLUSTERED 
	(
		[FEES_CD_FECHAMENTO],
		[TRAN_CD_TRANSACAO],
		[ATCA_CD_ATIVIDADE_CARGA],
		[MODU_CD_MODULO],
		[MEPR_CD_MEGA_PROCESSO],
		[PROC_CD_PROCESSO],
		[SUPR_CD_SUB_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FECHA_HISTORICO_ESCOPO] WITH NOCHECK ADD 
	CONSTRAINT [PK_FECHA_HISTORIO_ESCOPO] PRIMARY KEY  NONCLUSTERED 
	(
		[FEES_CD_FECHAMENTO],
		[TRAN_CD_TRANSACAO],
		[ATCA_CD_ATIVIDADE_CARGA],
		[MODU_CD_MODULO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FECHA_HISTORICO_TRANSACAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_FECHA_HISTORICO_TRANSACAO] PRIMARY KEY  NONCLUSTERED 
	(
		[TRAN_CD_TRANSACAO],
		[FEES_CD_FECHAMENTO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUNCAO_NEGOCIO] WITH NOCHECK ADD 
	CONSTRAINT [PK__FUNCAO_NEGOCIO__7DEF3CE1] PRIMARY KEY  NONCLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUNCAO_USUARIO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[USMA_CD_USUARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUN_NEG_CONFL] WITH NOCHECK ADD 
	CONSTRAINT [PK_FUN_NEG_CONFL] PRIMARY KEY  NONCLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[FUNC_CD_FUNCAO_CONFL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUN_NEG_ORG_AGLU] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[AGLU_CD_AGLUTINADO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUN_NEG_TP_QUA] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[TPQU_CD_TIPO_QUALIFICACAO],
		[FUNE_CD_FUNCAO_NEGOCIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[FUN_NEG_TRANSACAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_FUN_NEG_TRANSACAO] PRIMARY KEY  NONCLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[ATCA_CD_ATIVIDADE_CARGA],
		[TRAN_CD_TRANSACAO],
		[MODU_CD_MODULO],
		[PROC_CD_PROCESSO],
		[SUPR_CD_SUB_PROCESSO],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[GRUPO_VALIDADOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_GRUPO_VALIDADOR] PRIMARY KEY  NONCLUSTERED 
	(
		[MEPR_CD_MEGA_PROCESSO],
		[GRVA_TX_ASSUNTO],
		[USUA_CD_USUARIO],
		[GRVA_TX_TIPO2]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[HISTORICO_CENARIO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[HICE_NR_SEQUENCIAL],
		[CENA_CD_CENARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MACRO_HISTORICO_VALIDACAO] WITH NOCHECK ADD 
	CONSTRAINT [PK_MACRO_HISTORICO_VALIDACAO] PRIMARY KEY  NONCLUSTERED 
	(
		[MHVA_NR_SEQUENCIA_HIST],
		[MCPR_NR_SEQ_MACRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MACRO_OBJ_AUTORIZA] WITH NOCHECK ADD 
	CONSTRAINT [PK_MACRO_OBJ_AUTORIZA] PRIMARY KEY  NONCLUSTERED 
	(
		[TRAN_CD_TRANSACAO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MACRO_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK__MACRO_PERFIL__1B5FA437] PRIMARY KEY  NONCLUSTERED 
	(
		[MCPR_NR_SEQ_MACRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MACRO_PERFIL_FUN_NEG] WITH NOCHECK ADD 
	CONSTRAINT [PK_MACRO_PERFIL_FUN_NEG] PRIMARY KEY  NONCLUSTERED 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MACRO_PERFIL_TRANSACAO] WITH NOCHECK ADD 
	CONSTRAINT [PK__MACRO_PERFIL_TRA__2943AF3A] PRIMARY KEY  NONCLUSTERED 
	(
		[TRAN_CD_TRANSACAO],
		[MCPR_NR_SEQ_MACRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MAC_PER_TRAN_OBJETO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[TROB_TX_CAMPO],
		[TRAN_CD_TRANSACAO],
		[TROB_TX_OBJETO],
		[MCPR_NR_SEQ_MACRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MEGA_PROCESSO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MICRO_PERFIL] WITH NOCHECK ADD 
	CONSTRAINT [PK__MICRO_PERFIL__571DF1D5] PRIMARY KEY  NONCLUSTERED 
	(
		[MICR_TX_SEQ_MICRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MICRO_PERFIL_R3] WITH NOCHECK ADD 
	CONSTRAINT [PK_MICRO_PERFIL_R3] PRIMARY KEY  NONCLUSTERED 
	(
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MIPE_NR_SEQ_MICRO_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MODULO_R3] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[MODU_CD_MODULO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[MODU_ATIV_TRA_CARGA] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[TRAN_CD_TRANSACAO],
		[ATCA_CD_ATIVIDADE_CARGA],
		[MODU_CD_MODULO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[NOTICIA] WITH NOCHECK ADD 
	CONSTRAINT [PK__NOTICIA__4A19C7C9] PRIMARY KEY  NONCLUSTERED 
	(
		[NOTI_CD_NOTICIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ONDA] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[ONDA_CD_ONDA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[OPERACOES_ESPEC] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[OPES_CD_OPERACAO_ESP]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORGAO_AGLUTINADOR] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[AGLU_CD_AGLUTINADO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORGAO_MAIOR_OLD] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[ORLO_CD_ORG_LOT],
		[ORLO_NR_ORDEM]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[ORGAO_MENOR] WITH NOCHECK ADD 
	CONSTRAINT [PK_ORGAO_MENOR] PRIMARY KEY  NONCLUSTERED 
	(
		[ORME_CD_ORG_MENOR]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PERFIL] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[PERF_CD_PERFIL]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[PROCESSO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[PROC_CD_PROCESSO],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[RELACAO_FINAL] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[TRAN_CD_TRANSACAO],
		[ATCA_CD_ATIVIDADE_CARGA],
		[MODU_CD_MODULO],
		[MEPR_CD_MEGA_PROCESSO],
		[PROC_CD_PROCESSO],
		[SUPR_CD_SUB_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SITUACAO_GERAL] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[SITU_CD_SITUACAO_CHAVE]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SOLICITACAO_FUNCAO] WITH NOCHECK ADD 
	CONSTRAINT [DF_SOLICITACAO_FUNCAO_SOFU_IN_TREINAMENTO] DEFAULT (0) FOR [SOFU_IN_TREINAMENTO],
	CONSTRAINT [DF_SOLICITACAO_FUNCAO_SOFU_IN_CONFLITO] DEFAULT (0) FOR [SOFU_IN_CONFLITO]
GO

ALTER TABLE [dbo].[STATUS_USUARIO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[STUS_CD_STATUS]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SUB_MODULO_OLD] WITH NOCHECK ADD 
	CONSTRAINT [PK__SUB_MODULO__50528F63] PRIMARY KEY  NONCLUSTERED 
	(
		[SUMO_NR_CD_SEQUENCIA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SUB_PROCESSO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[MEPR_CD_MEGA_PROCESSO],
		[PROC_CD_PROCESSO],
		[SUPR_CD_SUB_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[SUB_PROCESSO_EMPRESA_UNIDADE] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[MEPR_CD_MEGA_PROCESSO],
		[PROC_CD_PROCESSO],
		[SUPR_CD_SUB_PROCESSO],
		[EMPR_CD_NR_EMPRESA]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TIPO_QUALIFICACAO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[TPQU_CD_TIPO_QUALIFICACAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TRANSACAO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[TRAN_CD_TRANSACAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TRANSACAO_DESENV] WITH NOCHECK ADD 
	CONSTRAINT [PK_TRANSACAO_DESENV] PRIMARY KEY  NONCLUSTERED 
	(
		[TRAN_CD_TRANSACAO],
		[DESE_CD_DESENVOLVIMENTO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TRANSACAO_MEGA] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[TRAN_CD_TRANSACAO],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TRANSACAO_OBJETO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[TROB_TX_CAMPO],
		[TROB_TX_OBJETO],
		[TRAN_CD_TRANSACAO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[USUARIO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[USUA_CD_USUARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[USUARIO_MAPEAMENTO] WITH NOCHECK ADD 
	CONSTRAINT [PK_USUARIO_MAPEAMENTO] PRIMARY KEY  NONCLUSTERED 
	(
		[USMA_CD_USUARIO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[USUARIO_ORGAO] WITH NOCHECK ADD 
	 PRIMARY KEY  NONCLUSTERED 
	(
		[ORME_CD_ORG_MENOR],
		[USMA_CD_USUARIO],
		[PERF_CD_PERFIL],
		[MEPR_CD_MEGA_PROCESSO]
	) WITH  FILLFACTOR = 10  ON [PRIMARY] 
GO

 CREATE  INDEX [_WA_Sys_MEPR_CD_MEGA_PROCESSO_60FC61CA] ON [dbo].[ACESSO]([MEPR_CD_MEGA_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_ATCA_TX_DESC_ATIVIDADE_10E07F16] ON [dbo].[ATIVIDADE_CARGA]([ATCA_TX_DESC_ATIVIDADE]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_ATCA_NR_SEQUENCIA_10E07F16] ON [dbo].[ATIVIDADE_CARGA]([ATCA_NR_SEQUENCIA]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_EMPR_CD_NR_EMPRESA_50C5FA01] ON [dbo].[ATIVIDADE_CARGA_EMPRESA_UNID]([EMPR_CD_NR_EMPRESA]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_TRAN_CD_TRANSACAO_5EAA0504] ON [dbo].[BPP_TRANSACAO]([TRAN_CD_TRANSACAO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_BUG_MEGA_PROCESSO_6B79F03D] ON [dbo].[BUG_IMPORT]([BUG_MEGA_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_BUG_NR_SEQUENCIA_6B79F03D] ON [dbo].[BUG_IMPORT]([BUG_NR_SEQUENCIA]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_MEPR_CD_MEGA_PROCESSO_542C7691] ON [dbo].[CENARIO]([MEPR_CD_MEGA_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_SUPR_CD_SUB_PROCESSO_542C7691] ON [dbo].[CENARIO]([SUPR_CD_SUB_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_PROC_CD_PROCESSO_542C7691] ON [dbo].[CENARIO]([PROC_CD_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_ONDA_CD_ONDA_542C7691] ON [dbo].[CENARIO]([ONDA_CD_ONDA]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_CLCE_CD_NR_CLASSE_CENARIO_542C7691] ON [dbo].[CENARIO]([CLCE_CD_NR_CLASSE_CENARIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_CENA_TX_CD_CENARIO_542C7691] ON [dbo].[CENARIO]([CENA_TX_CD_CENARIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_CENA_TX_GERA_FLUXO_542C7691] ON [dbo].[CENARIO]([CENA_TX_GERA_FLUXO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_CENA_TX_SITUACAO_542C7691] ON [dbo].[CENARIO]([CENA_TX_SITUACAO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_MEPR_CD_MEGA_PROCESSO_7226EDCC] ON [dbo].[CLASSE_CENARIO_MEGA_PROCESSO]([MEPR_CD_MEGA_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_CURS_CD_CURSO_04659998] ON [dbo].[CURSO]([CURS_CD_CURSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_CENA_CD_CENARIO_0FD74C44] ON [dbo].[CURSO_CENARIO]([CENA_CD_CENARIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_FUNE_CD_FUNCAO_NEGOCIO_0C06BB60] ON [dbo].[CURSO_FUNCAO]([FUNE_CD_FUNCAO_NEGOCIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_CURS_PRE_REQUSITO_1960B67E] ON [dbo].[CURSO_PRE_REQUISITO]([CURS_PRE_REQUISITO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_TRAN_CD_TRANSACAO_07420643] ON [dbo].[CURSO_TRANSACAO]([TRAN_CD_TRANSACAO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_fune_in_bloqueado_4A6E022D] ON [dbo].[FUNCAO_NEGOCIO]([FUNE_IN_BLOQUEADO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_1] ON [dbo].[FUNCAO_NEGOCIO]([MEPR_CD_MEGA_PROCESSO], [FUNE_CD_FUNCAO_NEGOCIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_usma_cd_usuario_2EC5E7B8] ON [dbo].[FUNCAO_USUARIO]([USMA_CD_USUARIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_1] ON [dbo].[FUNCAO_USUARIO]([FUNE_CD_FUNCAO_NEGOCIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_2] ON [dbo].[FUNCAO_USUARIO]([USMA_CD_USUARIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_3] ON [dbo].[FUNCAO_USUARIO]([FUNE_CD_FUNCAO_NEGOCIO], [USMA_CD_USUARIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_1] ON [dbo].[FUN_NEG_CONFL]([FUNE_CD_FUNCAO_NEGOCIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_2] ON [dbo].[FUN_NEG_CONFL]([FUNC_CD_FUNCAO_CONFL]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_AGLU_CD_AGLUTINADO_62108194] ON [dbo].[FUN_NEG_ORG_AGLU]([AGLU_CD_AGLUTINADO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_FUNE_CD_FUNCAO_NEGOCIO_3C54ED00] ON [dbo].[FUN_NEG_TP_QUA]([FUNE_CD_FUNCAO_NEGOCIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_CENA_CD_CENARIO_6E2152BE] ON [dbo].[HISTORICO_CENARIO]([CENA_CD_CENARIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_mepr_in_bloqueado_43C1049E] ON [dbo].[MEGA_PROCESSO]([MEPR_IN_BLOQUEADO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_MEPR_TX_DESC_MEGA_PROCESSO_43C1049E] ON [dbo].[MEGA_PROCESSO]([MEPR_TX_DESC_MEGA_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IX_MIPE] ON [dbo].[MICRO_PERFIL_R3]([MIPE_NR_SEQ_MICRO_PERFIL]) ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_MODU_CD_MODULO_1D4655FB] ON [dbo].[MODU_ATIV_TRA_CARGA]([MODU_CD_MODULO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_ATCA_CD_ATIVIDADE_CARGA_1D4655FB] ON [dbo].[MODU_ATIV_TRA_CARGA]([ATCA_CD_ATIVIDADE_CARGA]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_1] ON [dbo].[NOTICIA]([NOTI_DT_FIM], [NOTI_DT_INICIO], [PERF_CD_PERFIL], [ORME_CD_ORG_MENOR]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_orlo_cd_status_5303482E] ON [dbo].[ORGAO_MAIOR_OLD]([ORLO_CD_STATUS]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_orlo_in_bloqueado_5303482E] ON [dbo].[ORGAO_MAIOR_OLD]([ORLO_IN_BLOQUEADO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_orlo_sg_org_lot_5303482E] ON [dbo].[ORGAO_MAIOR_OLD]([ORLO_SG_ORG_LOT]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_ORLO_NM_ORG_LOT_5303482E] ON [dbo].[ORGAO_MAIOR_OLD]([ORLO_NM_ORG_LOT]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_1] ON [dbo].[ORGAO_MENOR]([ORME_CD_ORG_MENOR], [ORLO_CD_ORG_LOT]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_MEPR_CD_MEGA_PROCESSO_58671BC9] ON [dbo].[PROCESSO]([MEPR_CD_MEGA_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_PROC_NR_SEQUENCIA_58671BC9] ON [dbo].[PROCESSO]([PROC_NR_SEQUENCIA]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_PROC_TX_DESC_PROCESSO_58671BC9] ON [dbo].[PROCESSO]([PROC_TX_DESC_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_SITU_NR_SEQUENCIA_381A47C8] ON [dbo].[SITUACAO_GERAL]([SITU_NR_SEQUENCIA]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IX_SOPE_MIPE] ON [dbo].[SOLICITACAO_PERFIL]([MIPE_NR_SEQ_MICRO_PERFIL]) ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_PROC_CD_PROCESSO_24E777C3] ON [dbo].[SUB_PROCESSO]([PROC_CD_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_SUPR_CD_SUB_PROCESSO_24E777C3] ON [dbo].[SUB_PROCESSO]([SUPR_CD_SUB_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_SUPR_NR_SEQUENCIA_24E777C3] ON [dbo].[SUB_PROCESSO]([SUPR_NR_SEQUENCIA]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_SUPR_TX_DESC_SUB_PROCESSO_24E777C3] ON [dbo].[SUB_PROCESSO]([SUPR_TX_DESC_SUB_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_EMPR_CD_NR_EMPRESA_26CFC035] ON [dbo].[SUB_PROCESSO_EMPRESA_UNIDADE]([EMPR_CD_NR_EMPRESA]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_SUPR_CD_SUB_PROCESSO_26CFC035] ON [dbo].[SUB_PROCESSO_EMPRESA_UNIDADE]([SUPR_CD_SUB_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_PROC_CD_PROCESSO_26CFC035] ON [dbo].[SUB_PROCESSO_EMPRESA_UNIDADE]([PROC_CD_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_TRAN_TX_DESC_TRANSACAO_28B808A7] ON [dbo].[TRANSACAO]([TRAN_TX_DESC_TRANSACAO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_USUA_TX_CATEGORIA_5F141958] ON [dbo].[USUARIO]([USUA_TX_CATEGORIA]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_1] ON [dbo].[USUARIO_MAPEAMENTO]([ORME_CD_ORG_MENOR]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_2] ON [dbo].[USUARIO_MAPEAMENTO]([ORME_CD_ORG_MENOR], [USMA_CD_USUARIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_usma_cd_usuario_27E3DFFF] ON [dbo].[USUARIO_ORGAO]([USMA_CD_USUARIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_mepr_cd_mega_processo_27E3DFFF] ON [dbo].[USUARIO_ORGAO]([MEPR_CD_MEGA_PROCESSO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [_WA_Sys_PERF_CD_PERFIL_27E3DFFF] ON [dbo].[USUARIO_ORGAO]([PERF_CD_PERFIL]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

 CREATE  INDEX [IDX_1] ON [dbo].[USUARIO_ORGAO]([ORME_CD_ORG_MENOR], [USMA_CD_USUARIO]) WITH  FILLFACTOR = 10 ON [PRIMARY]
GO

setuser
GO

EXEC sp_bindefault N'[dbo].[VAL_INIC_CENA_TRAN]', N'[CENARIO_TRANSACAO].[CETR_TX_SITU_TESTE_CENARIO]'
GO

setuser
GO

ALTER TABLE [dbo].[FUNCAO_NEGOCIO_SUB_MODULO] ADD 
	CONSTRAINT [FK_FUNCAO_NEGOCIO_SUB_MODULO_FUNCAO_NEGOCIO] FOREIGN KEY 
	(
		[FUNE_CD_FUNCAO_NEGOCIO]
	) REFERENCES [dbo].[FUNCAO_NEGOCIO] (
		[FUNE_CD_FUNCAO_NEGOCIO]
	),
	CONSTRAINT [FK_FUNCAO_NEGOCIO_SUB_MODULO_SUB_MODULO] FOREIGN KEY 
	(
		[SUMO_NR_CD_SEQUENCIA]
	) REFERENCES [dbo].[SUB_MODULO] (
		[SUMO_NR_CD_SEQUENCIA]
	)
GO

ALTER TABLE [dbo].[LOG_CONFLITANTE] ADD 
	CONSTRAINT [FK_SOFU_LOCO] FOREIGN KEY 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	) REFERENCES [dbo].[SOLICITACAO_FUNCAO] (
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	)
GO

ALTER TABLE [dbo].[LOG_TREINAMENTO] ADD 
	CONSTRAINT [FK_SOFU_LOTR] FOREIGN KEY 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	) REFERENCES [dbo].[SOLICITACAO_FUNCAO] (
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	)
GO

ALTER TABLE [dbo].[SOLICITACAO_PERFIL] ADD 
	CONSTRAINT [FK_SOFU_SOPE] FOREIGN KEY 
	(
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	) REFERENCES [dbo].[SOLICITACAO_FUNCAO] (
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	)
GO

ALTER TABLE [dbo].[SOLICITACAO_PERFIL_VISAO] ADD 
	CONSTRAINT [FK_SOPE_SOPV] FOREIGN KEY 
	(
		[MIPE_NR_SEQ_MICRO_PERFIL],
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	) REFERENCES [dbo].[SOLICITACAO_PERFIL] (
		[MIPE_NR_SEQ_MICRO_PERFIL],
		[FUNE_CD_FUNCAO_NEGOCIO],
		[MCPR_NR_SEQ_MACRO_PERFIL],
		[MEPR_CD_MEGA_PROCESSO],
		[SOLI_CD_SOLICITACAO]
	)
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_GERAL] ADD 
	CONSTRAINT [FK_XPET_PLANO_TAREFA_GERAL_XPEP_PLANO_ENT_PRODUCAO] FOREIGN KEY 
	(
		[PLAN_NR_SEQUENCIA_PLANO]
	) REFERENCES [dbo].[XPEP_PLANO_ENT_PRODUCAO] (
		[PLAN_NR_SEQUENCIA_PLANO]
	)
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PAI] ADD 
	CONSTRAINT [FK_XPEP_PLANO_TAREFA_PAI_XPET_PLANO_TAREFA_GERAL] FOREIGN KEY 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) REFERENCES [dbo].[XPEP_PLANO_TAREFA_GERAL] (
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	)
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PCD] ADD 
	CONSTRAINT [FK_XPEP_PLANO_TAREFA_PCD_XPEP_SISTEMA_LEGADO] FOREIGN KEY 
	(
		[SIST_NR_SEQUENCIAL_SISTEMA_LEGADO]
	) REFERENCES [dbo].[XPEP_SISTEMA_LEGADO] (
		[SIST_NR_SEQUENCIAL_SISTEMA_LEGADO]
	),
	CONSTRAINT [FK_XPEP_PLANO_TAREFA_PCD_XPET_PLANO_TAREFA_GERAL] FOREIGN KEY 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) REFERENCES [dbo].[XPEP_PLANO_TAREFA_GERAL] (
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	)
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PCM] ADD 
	CONSTRAINT [FK_XPEP_PLANO_TAREFA_PCM_XPEP_PLANO_ENT_PRODUCAO] FOREIGN KEY 
	(
		[PLAN_NR_SEQUENCIA_PLANO]
	) REFERENCES [dbo].[XPEP_PLANO_ENT_PRODUCAO] (
		[PLAN_NR_SEQUENCIA_PLANO]
	)
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PDS] ADD 
	CONSTRAINT [FK_XPEP_PLANO_TAREFA_PDS_XPET_PLANO_TAREFA_GERAL] FOREIGN KEY 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) REFERENCES [dbo].[XPEP_PLANO_TAREFA_GERAL] (
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	)
GO

ALTER TABLE [dbo].[XPEP_PLANO_TAREFA_PPO] ADD 
	CONSTRAINT [FK_XPEP_PLANO_TAREFA_PPO_XPET_PLANO_TAREFA_GERAL] FOREIGN KEY 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) REFERENCES [dbo].[XPEP_PLANO_TAREFA_GERAL] (
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	)
GO

ALTER TABLE [dbo].[XPEP_TAREFA_RESPONSAVEL] ADD 
	CONSTRAINT [FK_XPEP_TAREFA_RESPONSAVEL_XPEP_EQUIPE_SINERGIA] FOREIGN KEY 
	(
		[USUA_TX_CD_USUARIO]
	) REFERENCES [dbo].[XPEP_EQUIPE_SINERGIA] (
		[USUA_TX_CD_USUARIO]
	),
	CONSTRAINT [FK_XPEP_TAREFA_RESPONSAVEL_XPEP_TIPO_RESPONSABILIDADE] FOREIGN KEY 
	(
		[TPRE_NR_TIPO_RESPONSABILIDADE]
	) REFERENCES [dbo].[XPEP_TIPO_RESPONSABILIDADE] (
		[TPRE_NR_TIPO_RESPONSABILIDADE]
	),
	CONSTRAINT [FK_XPEP_TAREFA_RESPONSAVEL_XPET_PLANO_TAREFA_GERAL] FOREIGN KEY 
	(
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	) REFERENCES [dbo].[XPEP_PLANO_TAREFA_GERAL] (
		[PLAN_NR_SEQUENCIA_PLANO],
		[PLTA_NR_SEQUENCIA_TAREFA]
	)
GO

