vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|21 Aug 2003 12:30:13 -0000
vti_extenderversion:SR|5.0.2.4330
vti_author:SR|CORP\\XD47
vti_modifiedby:SR|CORP\\XD47
vti_timecreated:TR|21 Aug 2003 12:30:13 -0000
vti_cacheddtm:TX|21 Aug 2003 12:30:13 -0000
vti_filesize:IR|37665
vti_cachedtitle:SR|SINERGIA # XPROC # Processos de Negócio
vti_cachedbodystyle:SR|<body bgcolor="#FFFFFF" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" onLoad="MM_preloadImages('../../imagens/novo_registro_02.gif')">
vti_cachedlinkinfo:VX|H|JavaScript:history.back() S|../../imagens/voltar.gif H|JavaScript:history.forward() S|../../imagens/avancar.gif H|JavaScript:window.external.AddFavorite('http://S6000WS12.corp.petrobras.biz/sinergia_total/index.htm','Sinergia\\ \\ -\\ X-Total') S|../../imagens/favoritos.gif H|javascript:print() S|../../imagens/imprimir.gif H|JavaScript:history.go() S|../../imagens/atualizar.gif H|../../indexA.asp S|../../imagens/home.gif H|selec_Mega_Proc_Sub_Cenario.asp S|../../imagens/selecao_F02.gif H|selec_Mega_Proc_Sub_Cenario.asp S|../../imagens/selecao_F02.gif H|selec_Mega_Proc_Sub_Cenario.asp S|../../imagens/selecao_F02.gif H|javascript:MM_goToURL9('self','alt_situacao.asp',this) S|../../imagens/novo_registro_02_off.gif H|selec_Mega_Proc_Sub_Cenario.asp S|../../imagens/selecao_F02.gif H|javascript:MM_goToURL4('self','cad_cenario_transacao.asp',this) S|../../imagens/novo_registro_02_off.gif H|javascript:MM_goToURL3('self','inc_oper_espe_exit_interface.asp',this) S|../../imagens/novo_registro_02_off.gif H|javascript:MM_goToURL6('self','cad_cenario_transacao.asp',this) S|../../imagens/novo_registro_02_off.gif H|javascript:MM_goToURL3('self','inc_oper_espe_manual.asp',this) S|../../imagens/novo_registro_02_off.gif H|javascript:MM_goToURL3('self','inc_chamada_cenario.asp',this) S|../../imagens/novo_registro_02_off.gif H|javascript:MM_goToURL3('self','inc_historico.asp',this) S|../../imagens/novo_registro_02_off.gif H|javascript:MM_goToURL5('self','alt_cenario_transacao.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') H|javascript:MM_goToURL5('self','alt_oper_espe_cena_tran.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') H|javascript:MM_goToURL5('self','alt_chamada_cenario.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') H|javascript:MM_goToURL5('self','alt_oper_espe_exit_interface.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') H|javascript:MM_goToURL5('self','exc_cenario_transacao.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') K|gerencia_cenario_transa.asp S|../../imagens/b011.gif H|javascript:MM_goToURL5('self','inc_bpp_transa_cenario.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') S|../../imagens/b04.gif
vti_cachedsvcrellinks:VX|SHUS|JavaScript:history.back() FSUS|imagens/voltar.gif SHUS|JavaScript:history.forward() FSUS|imagens/avancar.gif SHUS|JavaScript:window.external.AddFavorite('http://S6000WS12.corp.petrobras.biz/sinergia_total/index.htm','Sinergia\\ \\ -\\ X-Total') FSUS|imagens/favoritos.gif SHUS|javascript:print() FSUS|imagens/imprimir.gif SHUS|JavaScript:history.go() FSUS|imagens/atualizar.gif FHUS|indexA.asp FSUS|imagens/home.gif FHUS|asp/Cenario/selec_Mega_Proc_Sub_Cenario.asp FSUS|imagens/selecao_F02.gif FHUS|asp/Cenario/selec_Mega_Proc_Sub_Cenario.asp FSUS|imagens/selecao_F02.gif FHUS|asp/Cenario/selec_Mega_Proc_Sub_Cenario.asp FSUS|imagens/selecao_F02.gif SHUS|javascript:MM_goToURL9('self','alt_situacao.asp',this) FSUS|imagens/novo_registro_02_off.gif FHUS|asp/Cenario/selec_Mega_Proc_Sub_Cenario.asp FSUS|imagens/selecao_F02.gif SHUS|javascript:MM_goToURL4('self','cad_cenario_transacao.asp',this) FSUS|imagens/novo_registro_02_off.gif SHUS|javascript:MM_goToURL3('self','inc_oper_espe_exit_interface.asp',this) FSUS|imagens/novo_registro_02_off.gif SHUS|javascript:MM_goToURL6('self','cad_cenario_transacao.asp',this) FSUS|imagens/novo_registro_02_off.gif SHUS|javascript:MM_goToURL3('self','inc_oper_espe_manual.asp',this) FSUS|imagens/novo_registro_02_off.gif SHUS|javascript:MM_goToURL3('self','inc_chamada_cenario.asp',this) FSUS|imagens/novo_registro_02_off.gif SHUS|javascript:MM_goToURL3('self','inc_historico.asp',this) FSUS|imagens/novo_registro_02_off.gif SHUS|javascript:MM_goToURL5('self','alt_cenario_transacao.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') SHUS|javascript:MM_goToURL5('self','alt_oper_espe_cena_tran.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') SHUS|javascript:MM_goToURL5('self','alt_chamada_cenario.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') SHUS|javascript:MM_goToURL5('self','alt_oper_espe_exit_interface.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') SHUS|javascript:MM_goToURL5('self','exc_cenario_transacao.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') FKUS|asp/Cenario/gerencia_cenario_transa.asp FSUS|imagens/b011.gif SHUS|javascript:MM_goToURL5('self','inc_bpp_transa_cenario.asp',this,'<%=rdsCenario("CETR_NR_SEQUENCIA")%>') FSUS|imagens/b04.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1
vti_charset:SR|windows-1252
vti_title:SR|SINERGIA # XPROC # Processos de Negócio
vti_lineageid:SR|{A2E20CEB-F19B-4CB5-9227-AABB4A2FDCB9}
vti_backlinkinfo:VX|asp/Cenario/selec_Mega_Proc_Sub_Cenario.asp asp/Cenario/selec_Mega_Proc_Sub_Cenario2.asp asp/Cenario/cad_referencia_cenario.asp asp/Cenario/gerencia_cenario_transa.asp asp/Cenario/grava_operacoes_especiais.asp asp/Cenario/valida_cad_cenario_transacao.asp asp/Cenario/valida_altera_status.asp asp/Cenario/valida_altera_status_old.asp
