<tr> 
  <td width="100%"> 
    <table width="780" border="0">
      <tr> 
		<td width="20%" align="right"><a href="javascript: func_Alterar();" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('imgAlterar','','../img/alterar.gif',1)"><img name="imgAlterar" border="0" src="../img/alterar.gif" alt="Alterar"></a></td>      
        <td width="20%">&nbsp;</td>
        <td width="20%" align="center"><a href="javascript:func_Excluir();" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('imgExcluir','','../img/excluir.gif',1)"><img name="imgExcluir" border="0" src="../img/excluir.gif" alt="Excluir"></a></td>
        <td width="20%">&nbsp;</td>
        <td width="20%" align="left"><img name="imgVolta" border="0" onClick="history.back();" src="../img/000024.gif" alt="Voltar"></td>
      </tr>
    </table>
  </td>
</tr>