<tr> 
  <td width="100%"> 
    <table width="780" border="0">
      <tr>       
        <td width="40%" align="right"><img name="imaCONFIRMA1" border="0" onClick="Confirma();" src="../img/000036.gif" alt="Consultar"></td>
        <td width="20%">&nbsp;</td>
        <td width="40%" align="left"><img name="imgVolta" border="0" onClick="location.href='../index.asp';" src="../img/000024.gif" alt="Voltar"></td>
      </tr>
    </table>
  </td>
</tr>