<tr> 
  <td width="100%"> 
    <table width="780" border="0">
      <tr> 
		<td width="20%" align="right"><a href="javascript:Confirma();" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('imaCONFIRMA','','../img/000035.gif',1)"><img name="imaCONFIRMA" border="0" src="../img/000035.gif" alt="Enviar"></a></td>      
        <td width="20%">&nbsp;</td>
        <td width="20%" align="center"><a href="javascript:Limpa();" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image9','','../img/000034.gif',1)"><img name="Image9" border="0" src="../img/000034.gif" alt="Limpar"></a></td>
        <td width="20%">&nbsp;</td>
        <td width="20%" align="left"><img name="imgVolta" border="0" onClick="history.back();" src="../img/000024.gif" alt="Voltar"></td>
      </tr>
    </table>
  </td>
</tr>